version: '3'
services:
  db:
    platform: linux/x86_64
    image: mariadb:10.5.13
    networks:
      - net
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root_narita1005
      - MYSQL_DATABASE=db
      - MYSQL_USER=narita
      - MYSQL_PASSWORD=narinari1005
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./php/Dockerfile
    networks:
      - net
    volumes:
      - ./project:/var/www
    ports:
      - 8080:80
    restart: always
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=narita
      - PMA_PASSWORD=narinari1005
    networks:
      - net
    ports:
      - 8081:80
    volumes:
      - ./data/phpmyadmin:/sessions
    restart: always
networks:
  net: